### ISSUE TITLE
Enable password needed

### ISSUE THREAD

**Issue by technologyevangelist1** [routetehpacketz/cisco-ip-trace#13] opened 2020-04-12 14:07 UTC
i just copied the whole code and ran from my pc. but it  threw many tracebacks after it says "tracing ip" am I missing anything here? please help..new to this world

**Comment by routetehpacketz** [comment] 2020-04-13 12:36
it is hard to say without seeing the error, but my first question would be if you have the required modules installed.

**Comment by technologyevangelist1** [comment] 2020-04-14 14:56
Thanks for finding some time to respond. I have all the modules installed as far as I know. There were many trace backs. I am attaching the outputs in the file "error1". . Thank you.
[error1.txt](https://github.com/routetehpacketz/cisco-ip-trace/files/4476013/error1.txt)

**Comment by routetehpacketz** [comment] 2020-04-14 15:05
it looks like netmiko is unable to SSH into 10.44.86.1.

can you SSH into this device manually from the computer you are running the script on? does it require an enable password?

**Comment by technologyevangelist1** [comment] 2020-04-14 15:12
Yes, SSH is enabled on this device and in fact that is the only way to get inside. Telnet is disabled. This is a cisco 3560 model and it does require an "enable" password which is same as my "password"
Just to eliminate a device dependency, I have tried on a 4500 model also, and I got almost same trace backs.  Error attached
[error2.txt](https://github.com/routetehpacketz/cisco-ip-trace/files/4476102/error2.txt)

Do you think, I will uninstall python and all related modules and try from beginning to eliminate an issue in my PC.
 Thanks again for your help. Much appreciated

**Comment by technologyevangelist1** [comment] 2020-04-14 15:15
Forgot to mention. Yes, I can SSH into these devices from the same PC using a terminal program.

**Comment by routetehpacketz** [comment] 2020-04-14 15:58
hey, @technologyevangelist1 

thanks for supplying those text files illustrating the issue. the problem is that the netmiko command `enable()` is issued, but the script is not written to supply one. 

I have changed this issues label to reflect it is a bug. I will need to work on adding functionality of supplying an enable password (unique or re-using the supplied user password).

For the time being, if you want to run this script before I have completed adding this functionality, adding `privilege level 15` to your VTY lines' config will circumvent the requirement for an enable password. Alternatively, `aaa authorization` options may be used to omit the need for an enable password.

**Note that this may decrease security for accessing your devices. Please consult your company's policy and/or network administration before changing anything.**

I will comment again when this bug has been resolved with a test copy of the updated script for you to try. Please note this may take some time for me to address.

**Comment by technologyevangelist1** [comment] 2020-04-15 11:27
Thanks Man. Good to see the responsibility you are taking and really appreciated the way you are keeping this community alive. I will wait for the bug fix. Stay safe

**Comment by routetehpacketz** [comment] 2020-04-20 16:37
Hey, @technologyevangelist1, I have created a pull request to test support for enable passwords. can you copy the new version [from here](https://raw.githubusercontent.com/routetehpacketz/cisco-ip-trace/257a784e03a3653882e328cefdd59e1d4a717567/cisco_ip_trace.py) and test it?

Please test a few devices if possible.

**Comment by routetehpacketz** [comment] 2020-04-22 15:03
hey @technologyevangelist1, I just wanted to check in again and see if you have had the chance to test the updated version of the script I linked in my previous comment above.

**Comment by net9000** [comment] 2020-04-24 14:13
Been a minute since I ran these but when I tried to run it this is the output.  
```
(p3-env) ub18:/local$ ./enable.py
./enable.py: line 1: mport: command not found
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
from: can't read /var/mail/netmiko
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
from: can't read /var/mail/socket
./enable.py: line 15: csv_header: command not found
./enable.py: line 16: csv_line_template: command not found
./enable.py: line 23: syntax error near unexpected token `('
./enable.py: line 23: `ip_regex=re.compile(r'[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')'
```

**Comment by routetehpacketz** [comment] 2020-04-24 15:32
thanks for testing, @net9000. let me see if I am missing the secret password in the function for connecting to a switch after the core.

**Comment by routetehpacketz** [comment] 2020-04-24 17:55
ya I missed something. try the latest [here](https://raw.githubusercontent.com/routetehpacketz/cisco-ip-trace/026407e3b9e5fa28b09e3579696be4e769102517/cisco_ip_trace.py).

**Comment by net9000** [comment] 2020-04-24 19:25
It worked on a device that requires an enable pw.  

p3-env) dpatten@dpatten-ub18:/local-dp$ sudo ./enable-v2.py
Enter target in CIDR notation (192.168.10.0/24): 10.103.16.0/24
Enter VRF for the IP (leave blank if not needed):
Enter the IP address of the core router/switch that can ARP for the IP address to trace: 10.103.1.1
Username: administrator
Password:
Enable password (leave blank if not needed):
Enter a filename to save output as CSV (leave blank for no file output): test-enable16.csv

Tracing 10.103.16.1...Port Unknown
Device IP,Reverse DNS Name,MAC Address,Switch,Port,Port Description,Interface Type,VLANs on port,Port MAC count
10.103.16.1,00b6.70b2.91d6,r1x798xx,Unknown

**Comment by routetehpacketz** [comment] 2020-04-24 19:34
Thanks for testing. I haven't heard from @technologyevangelist1 yet, but I think this is evidence enough it will work so I'm going to close this out and merge the changes.

**Closed** 2020-04-24 20:33 UTC
Labels: bug, good first issue

**Comment by technologyevangelist1** [comment] 2020-09-25 20:26
Just wanted to come back to this. I tested it today and it worked like a charm. Thanks brother. I owe you a beer.
